<?php

namespace AppBundle\Repository;

/**
 * etablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class etablissementRepository extends \Doctrine\ORM\EntityRepository
{
}
