<?php

namespace AppBundle\Repository;

/**
 * imageEtablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class imageEtablissementRepository extends \Doctrine\ORM\EntityRepository
{
}
